#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "🛑 STOP, you are committing on branch 'main'!"
  echo "Please create new branch (git checkout -b feature/...)."
  exit 1
fi

npx lint-staged